
package com.example.consumingwebservice.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SOAPDemoSoap", targetNamespace = "http://tempuri.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPDemoSoap {


    /**
     * 
     * @param arg2
     * @param arg1
     * @return
     *     returns long
     */
    @WebMethod(operationName = "AddInteger", action = "http://tempuri.org/SOAP.Demo.AddInteger")
    @WebResult(name = "AddIntegerResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "AddInteger", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.AddInteger")
    @ResponseWrapper(localName = "AddIntegerResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.AddIntegerResponse")
    public long addInteger(
        @WebParam(name = "Arg1", targetNamespace = "http://tempuri.org")
        Long arg1,
        @WebParam(name = "Arg2", targetNamespace = "http://tempuri.org")
        Long arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @return
     *     returns long
     */
    @WebMethod(operationName = "DivideInteger", action = "http://tempuri.org/SOAP.Demo.DivideInteger")
    @WebResult(name = "DivideIntegerResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "DivideInteger", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.DivideInteger")
    @ResponseWrapper(localName = "DivideIntegerResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.DivideIntegerResponse")
    public long divideInteger(
        @WebParam(name = "Arg1", targetNamespace = "http://tempuri.org")
        Long arg1,
        @WebParam(name = "Arg2", targetNamespace = "http://tempuri.org")
        Long arg2);

    /**
     * 
     * @param id
     * @return
     *     returns com.example.consumingwebservice.wsdl.Person
     */
    @WebMethod(operationName = "FindPerson", action = "http://tempuri.org/SOAP.Demo.FindPerson")
    @WebResult(name = "FindPersonResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "FindPerson", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.FindPerson")
    @ResponseWrapper(localName = "FindPersonResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.FindPersonResponse")
    public Person findPerson(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org")
        String id);

    /**
     * 
     * @param name
     * @return
     *     returns com.example.consumingwebservice.wsdl.DataSet
     */
    @WebMethod(operationName = "GetByName", action = "http://tempuri.org/SOAP.Demo.GetByName")
    @WebResult(name = "GetByNameResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "GetByName", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetByName")
    @ResponseWrapper(localName = "GetByNameResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetByNameResponse")
    public DataSet getByName(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns com.example.consumingwebservice.wsdl.ByNameDataSet
     */
    @WebMethod(operationName = "GetDataSetByName", action = "http://tempuri.org/SOAP.Demo.GetDataSetByName")
    @WebResult(name = "GetDataSetByNameResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "GetDataSetByName", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetDataSetByName")
    @ResponseWrapper(localName = "GetDataSetByNameResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetDataSetByNameResponse")
    public ByNameDataSet getDataSetByName(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns com.example.consumingwebservice.wsdl.ArrayOfPersonIdentificationPersonIdentification
     */
    @WebMethod(operationName = "GetListByName", action = "http://tempuri.org/SOAP.Demo.GetListByName")
    @WebResult(name = "GetListByNameResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "GetListByName", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetListByName")
    @ResponseWrapper(localName = "GetListByNameResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.GetListByNameResponse")
    public ArrayOfPersonIdentificationPersonIdentification getListByName(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org")
        String name);

    /**
     * 
     * @param zip
     * @return
     *     returns com.example.consumingwebservice.wsdl.Address
     */
    @WebMethod(operationName = "LookupCity", action = "http://tempuri.org/SOAP.Demo.LookupCity")
    @WebResult(name = "LookupCityResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "LookupCity", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.LookupCity")
    @ResponseWrapper(localName = "LookupCityResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.LookupCityResponse")
    public Address lookupCity(
        @WebParam(name = "zip", targetNamespace = "http://tempuri.org")
        String zip);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Mission", action = "http://tempuri.org/SOAP.Demo.Mission")
    @WebResult(name = "MissionResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "Mission", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.Mission")
    @ResponseWrapper(localName = "MissionResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.MissionResponse")
    public String mission();

    /**
     * 
     * @param name
     * @return
     *     returns com.example.consumingwebservice.wsdl.QueryByNameDataSet
     */
    @WebMethod(operationName = "QueryByName", action = "http://tempuri.org/SOAP.Demo.QueryByName")
    @WebResult(name = "QueryByNameResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "QueryByName", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.QueryByName")
    @ResponseWrapper(localName = "QueryByNameResponse", targetNamespace = "http://tempuri.org", className = "com.example.consumingwebservice.wsdl.QueryByNameResponse")
    public QueryByNameDataSet queryByName(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org")
        String name);

}
